### PR TITLE
Merging again

### PR DESCRIPTION
**Pull request by ruth-farrell**
Fixing Issue #24 and trying to sort out the css on the booklist.

### CODE REVIEW

**Comment by staplesad** [comment]
Did it break something for you?

**Comment by ruth-farrell** [comment]
Yes - getting internal server error on the wish list page

**Comment by ruth-farrell** [comment]
NVM. Internal server error was through the live version. This is through my local: 
image

**Comment by staplesad** [comment]
Yep. I need to make sure that the database can handle having no entries in a new table. :/ sorry fixing it now.

**Pull request merged**
