### PR TITLE
Changing up Buttons

### PR DESCRIPTION
**Pull request by ruth-farrell**

### CODE REVIEW

**Comment by staplesad** [comment]
@ruth-farrell Did you mean to leave the 'leave review' button at the bottom of the page as well as putting it on the top right? 
screen shot 2017-06-11 at 20 19 40

**Comment by ruth-farrell** [comment]
Yep. The idea being that usually the bottom button is below the fold.  Should look like this though:
screen shot 2017-06-11 at 20 20 08

**Comment by staplesad** [comment]
Nope still looks like my screenshot. I'll double check the css on the heroku version is the same as the public css. Yeah same css. Not sure what the difference is.

**Comment by ruth-farrell** [comment]
image
That's what the current live version looks like, and this is what my local one looks like: 
image

The github version matches my local one. 
image

**Comment by ruth-farrell** [comment]
OOooooo Seems fine now. I cleared my cache and the live one caught up!!! Or did you do something? haha

**Comment by staplesad** [comment]
Lol nope. Mine was cached too I think.

**Pull request merged**
